### ISSUE TITLE
Cannot scroll down PM result page on window

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1630]
From: lironisraely@mail.tau.ac.il

Project: https://arbimon.org/project/riparian-biodiversity/analysis/patternmatching/79022

https://github.com/user-attachments/assets/5bed56e0-0b9d-40b9-90ca-1cd76d102bfa

![Image](https://github.com/user-attachments/assets/3713e9b0-a9e1-4ff0-a7d3-9106d383da3d)

**Comment by rassokhina-e** [comment]
Fixed, can check in 30 mins

**Comment by koonchaya** [comment]
I still see this issue with smaller window. https://github.com/user-attachments/assets/90dcc294-f7f8-4f6e-8433-8ea05fd70ba2
@rassokhina-e

**Comment by koonchaya** [comment]
Test job on staging https://staging.arbimon.org/project/bci-panama-2018/analysis/patternmatching/293
https://github.com/user-attachments/assets/c844f81b-f3ff-4fec-a3b0-0ec261a6008e

**Comment by koonchaya** [comment]
Now I see the problem on my mac (after latest production release 15 Nov 2024)
https://github.com/user-attachments/assets/9cc245dc-001b-4f5a-9184-90cb28d674a5
